### ISSUE TITLE
Markdown: Caption for code blocks

### ISSUE THREAD

**Issue by feedm3** [satellytes/satellytes.com#102]
We want to have captions on our images and code blocks. In Notion, it looks like this:

<img width="749" alt="Screenshot 2021-07-16 at 08 37 36" src="https://user-images.githubusercontent.com/7814926/125903364-2c262dc5-3cf7-48ba-b97b-6032c6276c14.png">

Not sure about the implementation and standard for captions on code blocks, there needs to be some research done on how to do it for CodeBlocks

**Comment by milljoniaer** [comment]
This has been covered through #550
