### ISSUE TITLE
Migrate Gatsby files to TypeScript

### ISSUE THREAD

**Issue by feedm3** [satellytes/satellytes.com#114]

**Comment by georgiee** [comment]
yeah that would be cool so I don't have to switch my programming context from those different bases🙏

**Comment by milljoniaer** [comment]
I tried to migrate all the gatsby config, node etc. files to Typescript, but as far as I can say, it is not easy to accomplish.

According to this [Github Issue](https://github.com/gatsbyjs/gatsby/issues/1457) it is possible to use this [Gatsby Plugin](https://www.gatsbyjs.com/plugins/gatsby-plugin-ts-config/) to forward a custom Typescript Gatsby Config inside the native JS config file. But you would still need the JS file. Gatsby is always searching for the `gatsby-config.js` file, no matter what you do.

In my opinion, the benefit that would be gained from this change does not outweigh the effort required.
- Compile-time type safety is not needed for files only used on startup
- The files are not changed that often

Thats why I close this Issue

**Comment by georgiee** [comment]
Kyle edited his comment from 2017 and added:

> Edit: This comment was written years ago when Typescript was much less popular. Most of the framework code is now written in Typescript. We're very open to community PRs adding better support for Typescript to core files.


So this might come to Gatsby, but until then I think it's fine to ditch the idea. We are good with the current situation anyway. Thanks!
