### ISSUE TITLE
Optimize `sitemal.xml` for multi language content

### ISSUE THREAD

**Issue by feedm3** [satellytes/satellytes.com#119]
We want to show our users the correct language of our site in the Google search results. There are multiple ways to tell Google which page to pick, the `sitemap.xml` is one of them. Therefore we should optimize it.

According to the docs, we need to change the structure like this: https://developers.google.com/search/docs/advanced/crawling/localized-versions#sitemap

Our current `sitemap.xml` is here: https://satellytes.com/sitemap/sitemap-0.xml

**Comment by georgiee** [comment]
this was done with PR #128 🙌
