### ISSUE TITLE
How to trigger a build easily? (to update jobs)

### ISSUE THREAD

**Issue by georgiee** [satellytes/satellytes.com#134]
As we all know Personio doesn't offer any type of webhooks for their Jobs API. This means when we update one of our job positions we won't see it reflected on the website. How can we help non-technical people to trigger a build once they update the content. Can we offer a "red button" to push? Should we build a pulling script, that knows when something has changed on the API to trigger a build ? Any other ideas?

**Comment by feedm3** [comment]
With Gatsby 4 supporting SSR we can think about using this rendering technique for the career pages.

Things to note:
SSR Caching is currently not supported out of the box. We have to do this manually with appropriate caching headers or API caching in the server function itself. As we don't have much traffic this shouldn't be a large problem, but something to think about.

Resources:
- https://v4.gatsbyjs.com/docs/how-to/rendering-options/using-server-side-rendering

**Comment by georgiee** [comment]
and it's an excellent playground for that new feature 😁👍

**Comment by georgiee** [comment]
SSR is one way the other one is to go over the actions and trigger the curl to let gatsby build again (via https://github.com/satellytes/satellytes.com/actions/workflows/scheduled-deployment.yml). I didn't know this when I opened this issue and I'm totally happy with that "red button". Done.
