### ISSUE TITLE
Show visual feedback after copying a code block

### ISSUE THREAD

**Issue by feedm3** [satellytes/satellytes.com#136]
After clicking on "Copy", we want to show the user visual feedback.

Github does it like this:

https://user-images.githubusercontent.com/7814926/133559909-c80b1b41-d688-433f-abfb-22fea2ed94b6.mp4

@georgiee already did some experiments, which you can read here: https://github.com/satellytes/satellytes.com/pull/130#issuecomment-913462511

**Comment by georgiee** [comment]
Jonathan is working on that.
