### ISSUE TITLE
Component: Navigation/Footer

### ISSUE THREAD

**Issue by fischeversenker** [satellytes/satellytes.com#154]
### Design
https://www.figma.com/file/FWlI63N28LP7BxqNqj1bGw/sy-004-(Design!)?node-id=3655%3A25488

### Things to consider
- Ca we reuse the existing `Navigation`?
- The menu is expected to be [animated](https://www.figma.com/file/FWlI63N28LP7BxqNqj1bGw/sy-004-(Design!)?node-id=122%3A1191) when "opened" via the hamburger button. I suggest to add this feature at a later point.

### Expected outcome
A component called `Navigation` that complies to the design.

**Comment by georgiee** [comment]
I will examine the existing navigation. Ideally it's already shared across the different places so I can provide a story and necessary refactorings if any.

**Comment by georgiee** [comment]
FYI This will need the introduction of the i18next plugin for storybook to provide our translations:
https://storybook.js.org/addons/storybook-react-i18next

We need to align the follow configuration with the guide from storybook: (like a different namespace etc)
https://github.com/microapps/gatsby-plugin-react-i18next/blob/e507e23157c3a6d66bfa6f7e0acd08f5f656ff67/src/plugin/wrapPageElement.tsx#L128-L138

**Comment by georgiee** [comment]
I renamed this issue to `Navigation/Footer` as we have a combined component (kind of). We can now use this place to coordinate our efforts. I will move forward and try to solve the edge case when people open the navigation being at the bottom already.

**Comment by georgiee** [comment]
we have worked on that let's plan through #254 where to continue.
