### ISSUE TITLE
Component: Icon Illustrations

### ISSUE THREAD

**Issue by fischeversenker** [satellytes/satellytes.com#157]
### Design
https://www.figma.com/file/FWlI63N28LP7BxqNqj1bGw/sy-004-(Design!)?node-id=3659%3A25045

### Things to consider
- Which of the existing Icons is still of any use?
- In Figma there seem to be mostly unique names but there are already duplicates (like "satellite"). How do we deal with this?

### Expected outcome
A new component that can be used to show any of the given illustration icons.

**Comment by georgiee** [comment]
Thank you @hofmann-felix for pointing me to this issue.
I think the best way to make those illustrations accessible are by exposing them through a central export/place so people now what's available. I'm thinking of a central curated place named `illustrations` (those are not icons). That place will give each svg a proper name and everyone will know where to get the illustrations.

```
// illustrations.ts: our central illustration curation

export ShootingStar from '../../illustrations/shooting-star.svg';
export ConstellationBigDipper from '../../illustrations/constellation-big-dipper.svg';
```

and later you can easily access them:
```
import { ShootingStar } from './llustrations';
// then use in jsx <ShootingStar/>


// or maybe bad for tree shaking:
import * as illustrations from './llustrations';

// jsx usage: <illustrations.ShootingStar/>
```

**Comment by georgiee** [comment]
Working on this. I had to export all files from Figma manually, then I used the OSX Automator to clean up the file names and after that I removed the explicit sizes from all svg files with sed:

```
find . -name "*.svg" -type f -exec sed -i  "" 's/ width="144" height="144"//g' {} \;
```

Now I have a folder with SVG which I export and that I can process with Storybook.
