### ISSUE TITLE
Component: Pagination Button

### ISSUE THREAD

**Issue by fischeversenker** [satellytes/satellytes.com#168]
### Design
- prev
https://www.figma.com/file/FWlI63N28LP7BxqNqj1bGw/sy-004-(Design!)?node-id=3719%3A16569

- next
https://www.figma.com/file/FWlI63N28LP7BxqNqj1bGw/sy-004-(Design!)?node-id=3719%3A16570

### Things to consider
- Take the "Hover" rules into account: https://www.figma.com/file/FWlI63N28LP7BxqNqj1bGw/sy-004-(Design!)?node-id=122%3A1191

### Expected outcome
A new component that can be used as both Prev and Next button **or** two dedicated components (e.g. `PaginationButtonNext` and `PaginationButtonPrev`). This is up to the implementer.

**Comment by georgiee** [comment]
I don't see us working on that anytime soon. maybe once we touch the blog.
