### ISSUE TITLE
Component: Button (copy)

### ISSUE THREAD

**Issue by fischeversenker** [satellytes/satellytes.com#169]
### Design
https://www.figma.com/file/FWlI63N28LP7BxqNqj1bGw/sy-004-(Design!)?node-id=3708%3A14588

### Things to consider
- Take the "Hover" rules into account: https://www.figma.com/file/FWlI63N28LP7BxqNqj1bGw/sy-004-(Design!)?node-id=122%3A1191

**Comment by georgiee** [comment]
This existing issue is important for the completion #136
