### ISSUE TITLE
Component: Teaser

### ISSUE THREAD

**Issue by fischeversenker** [satellytes/satellytes.com#173]
### Design
https://www.figma.com/file/FWlI63N28LP7BxqNqj1bGw/sy-004-(Design!)?node-id=3732%3A26923

### Things to consider
- Can we reuse the TextBlock and the Icon component for this?
- Take the "Hover" rules into account: https://www.figma.com/file/FWlI63N28LP7BxqNqj1bGw/sy-004-(Design!)?node-id=122%3A1191

**Comment by hofmann-felix** [comment]
A first version of the teaser component is already implemented (https://github.com/satellytes/satellytes.com/pull/181).
However, there are still a few outstanding issues (thanks to @georgiee for the feedback):

**WIP**
- Storybook: Create a story where you can see many teasers on one page (with CSS Grid) https://github.com/satellytes/satellytes.com/pull/198
- Storybook: hide the `cover` prop in the control section when it is used with an `<img/>` https://github.com/satellytes/satellytes.com/pull/198

**To Do**
- Replace the CSS spaghetti architecture for the hover effect with a `hover` prop that you can pass into the component
- Split the `cover` prop into an `illustration` and a `cover` (for images) prop
- The margin between headline and text depends on whether it is an image or an illustration. The design in Figma is correct and must be implemented.

**Comment by fischeversenker** [comment]
I'll reopen this. Let's close it once we are aligned with the designs.

**Comment by georgiee** [comment]
whatever is left let's handle through #254
