### ISSUE TITLE
Docs & MDX Support

### ISSUE THREAD

**Issue by georgiee** [satellytes/satellytes.com#185]
I would like to write a few words about our new components so people understand how and why you will use it. That's available in storybook through DocsPages.  It either extracts comments from a component or you start with mdx in the beginning, basically writing markdown content mixed with your components mark up.

See the [Docs Overview](https://github.com/storybookjs/storybook/tree/next/addons/docs) and the [MDX description](https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/mdx.md).

Right now my comments above components are not extracted. Maybe someone knows if this is already supported out of the box and then let's discuss if we would benefit from mdx.

**Comment by georgiee** [comment]
Maybe @feedm3 can help making mdx work. ideally make it the default view.
That way we can support a more design system approach were things are explained properly (and team design can provide explanations).

**Comment by hofmann-felix** [comment]
The mdx documentation is already supported by the storybook plugin `addon-essentials`. Besides `component-name.stories.tsx` you can also create a `component-name.stories.mdx` file. The stories from the tsx file can then be imported into the mdx file. I did this for the teaser to show the functionality: https://github.com/satellytes/satellytes.com/pull/200

@feedm3 added automatic storybook deployment for each PR.  

Instructions and further options can be found here:
- [How to write CSF stories with MDX docs](https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#csf-stories-with-mdx-docs)
- [General story book mdx documentation](https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/mdx.md)
