### ISSUE TITLE
Codeowners & PR assignments

### ISSUE THREAD

**Issue by georgiee** [satellytes/satellytes.com#186]
I think we should provide a [codeowners](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) file like in our client projects to assign people automatically.

Right now some assign reviewers and others do not. We still pick PRs up as we have the notifications enabled but I think a more explicit assignment would be great. We could even use a load balancing technique (round robin etc) to ensure people are not overloaded with PRs.

What do you think?
Thanks @hofmann-felix for asking the review assignment question before 👍

**Comment by fischeversenker** [comment]
I like it! Right now I'm carefully trying to review any PR that has not received any reviews yet or that has conflicting opinions in the existing reviews. A more structured approach would be nice and I like the idea of auto-assignments and a load balancing technique.
I had a look at the [GitHub documentation](https://docs.github.com/en/enterprise-cloud@latest/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team) and it seems that this is possible out of the box. Does that work with our current pricing model ("Enterprise Cloud"?)?

**Comment by georgiee** [comment]
I have created a team, enabled auto assignent for this repo and the load balancing algorithm. I think we don't need any codeowner file as it's a single team, so we should be good. Closing this issue. If things are off let's discuss it here.

You can find the seetings in the team options under [Code Review](https://github.com/orgs/satellytes/teams/website-crew/edit/review_assignment)
