### ISSUE TITLE
Words matter: rename branch "master"

### ISSUE THREAD

**Issue by miffili** [satellytes/satellytes.com#20]
Hey fellow Satellytes-devs! 🤓

I just saw this thread on twitter (https://bit.ly/2UsqyND) & have been thinking about it for a while now.. so I wanna suggest, we rename our `master` branch to `default` or `main`. (Or `principal`, `prime`, ..?)
I am aware that change feels uncomfortable. But it is a minor change for us and I think one that is necessary & good. As Georgios once said: words matter. And small things matter.

As far as I can see, it is possible to adapt our set up regarding deployment by changing one line in the `continous-deployment.yml`?

So? What do you say?
@georgiee @erinfm @feedm3

**Comment by georgiee** [comment]
Excellent, thanks for the reference. Let's do this. I already successfully changed my vocabulary for dumb & smart to presentational & container as I felt really stupid using such an analogy. I'm sure this works here too.

In the linked tweet you can also read about git/master. It came to me as a surprise to see `master` in terms of git versioning origin in master/slave than in "master copy".

I would go for `main`. Let's try how it feels in our daily routine with this repo. I consider this our "safe space" far away from any client where such a change can get difficult. The comfort zone where things usually not change can be a pretty violent place — even if it's only a word.

**Comment by erinfm** [comment]
Hello! I completely agree, words matter. Let's go for `main` or `default` then  👍

**Comment by feedm3** [comment]
Let's do this! 

I was thinking about some potential issues that could arise: `default` is a reserved word in a lot of programming languages, so I would go with `main`. Some external services may be limited to the `master` branch as default, but let's wait until that gets a real issue.

The github workflows and the protected branches need to be changed, that that should be a one-liner.

**Comment by miffili** [comment]
Okay, then we all agree. 🤓 🎉

Let's rename the branch to `main`. @feedm3 maybe you could pick up this task, as I imagine, there are some adjustments necessary in the pipeline?

**Comment by feedm3** [comment]
Will do it ASAP 🏃

**Comment by feedm3** [comment]
Done 🎉 

For future reference:
- Change branchName in Github Actions: https://github.com/satellytes/satellytes.com-new/blob/main/.github/workflows/continous-deployment.yml#L14
- Change default branch in Github Settings: <img width="761" alt="CleanShot 2020-06-16 at 09 58 33@2x" src="https://user-images.githubusercontent.com/7814926/84747866-22bee300-afb8-11ea-96c5-1126f859e0a3.png">
- Change netlify production branch: <img width="925" alt="CleanShot 2020-06-16 at 09 58 16@2x" src="https://user-images.githubusercontent.com/7814926/84747913-35391c80-afb8-11ea-9ba7-f7c780a99b5c.png">

**Comment by georgiee** [comment]
Thank youuuu 🤩
