### ISSUE TITLE
Quote component: add cite sources and other quote information

### ISSUE THREAD

**Issue by hofmann-felix** [satellytes/satellytes.com#221]
Currently, the Quote ContentBlock only shows the text as a formatted quote. @georgiee suggested that it would be useful to display more information (e.g. quote source, author, ...). This would work with the `figure` tag and this [documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote):
```
<figure>
    <blockquote cite="https://www.huxley.net/bnw/four.html">
        <p>Words can be like X-rays, if you use them properly—they’ll go through anything. You read and you’re pierced.</p>
    </blockquote>
    <figcaption>—Aldous Huxley, <cite>Brave New World</cite></figcaption>
</figure>
```

## Preview of the current quote component
<img width="553" alt="Bildschirmfoto 2021-11-29 um 08 43 55" src="https://user-images.githubusercontent.com/57712895/143827465-669cc8fc-de3b-4162-924e-e73fee582609.png">

**Comment by georgiee** [comment]
I think we have delivered this? Otherwise we can close this because it's not required right. Now. Maybe someone can check on that. Thanks.

**Comment by milljoniaer** [comment]
We do not have this feature for Blog Posts right now. Our current Contentful Model does not provide the opportunity to add an author or anything like that to a quote. Quotes are handled by the stock contentful rich text functionality.

 If we need this right now, we have to add custom quotes to our contentful model.

**Comment by milljoniaer** [comment]
As I dont think that we need this now, I close this issue for now
