### ISSUE TITLE
Button Issues

### ISSUE THREAD

**Issue by georgiee** [satellytes/satellytes.com#228]
Our button is based on a real button element. That's good.

The implementation looks odd though:
https://github.com/satellytes/satellytes.com/blob/07e2040d4e548c0a6d4c368b1369b5a8acd9ab95/src/components/buttons/button.tsx#L29-L37

You can see that there is a dedicated `onClick` event handler whereas I would have expected to spread the props to pass through any option that is valid for a button (disabled, onClick and such).

Something like that:

```
export interface ButtonProps extends React.ComponentPropsWithoutRef<"button"> {
// additional props if any
}

const Button = (props: ButtonProps) => {
  return (
    <StyledButton {...props}>
      <ButtonText>{props.children}</ButtonText>
```

This is a much nicer citizen of a UI component library, isn't it ?

**Comment by fischeversenker** [comment]
Sounds good 👌 

What's the benefit of inheriting from `React.ComponentPropsWithoutRef<"button">`? Does it include `children` and similar inbuilt props? Does the generic refer to the actual HTML element "button" and thus allows for `disabled` and similar attributes?

**Comment by georgiee** [comment]
Exactly as you describe it 👍 I would like to pass any valid button property by spreading the props. Actually I like quite the opposite, I want to be very explicit. Because what helps to pass in `disabled` if it's not reflected by the design. But right now the requirements are a mess and I think we will grow once we use it.

Here a good example of a button component how I imagine it. They also have the difference between button and linked baked into the component to switch the underlying implementation if it's a non-interactive link. 

https://github.com/wfp/designsystem/blob/191834bd01a1ae8d793f154498336f1f584b72c6/src/components/Button/Button.js#L83-L108


Hera a diff how I stashed it before when I tinkered around:

```diff

diff --git a/src/components/buttons/button.stories.tsx b/src/components/buttons/button.stories.tsx
index 6085ffe..e7cb76a 100644
--- a/src/components/buttons/button.stories.tsx
+++ b/src/components/buttons/button.stories.tsx
@@ -1,20 +1,21 @@
 import React from 'react';
 import { ComponentStory, ComponentMeta } from '@storybook/react';
-import Button from './button';
+import { Button } from './button';
 
 export default {
   component: Button,
   title: 'Components/Button',
   argTypes: {
-    onClick: { action: 'onChange' },
+    onClick: { action: 'onButtonClicked' },
   },
 } as ComponentMeta<typeof Button>;
 
 const Template: ComponentStory<typeof Button> = (args) => (
-  <Button {...args}></Button>
+  <Button {...args}/>
 );
 
 export const Regular = Template.bind({});
+
 Regular.args = {
-  children: 'Alle Services',
+  children: 'Alle Services'
 };
diff --git a/src/components/buttons/button.tsx b/src/components/buttons/button.tsx
index eb6c07c..6fd7851 100644
--- a/src/components/buttons/button.tsx
+++ b/src/components/buttons/button.tsx
@@ -26,15 +26,12 @@ const ButtonText = styled.span`
   color: #ffffff;
 `;
 
-interface RegularButtonProps {
-  children: React.ReactNode;
-  onClick: React.MouseEventHandler;
-}
+export type ButtonProps = React.ComponentPropsWithoutRef<"button">;
 
-const Button = ({ children, onClick }: RegularButtonProps) => {
+export const Button = (props: ButtonProps) => {
   return (
-    <StyledButton onClick={(event) => onClick?.(event)}>
-      <ButtonText>{children}</ButtonText>
+    <StyledButton {...props}>
+      <ButtonText>{props.children}</ButtonText>
       <StyledIcon>
         <svg
           width="7"
@@ -52,7 +49,5 @@ const Button = ({ children, onClick }: RegularButtonProps) => {
         </svg>
       </StyledIcon>
     </StyledButton>
-  );
+  )
 };
-
-export default Button;



```

Will such a change help or hurt ?

**Comment by feedm3** [comment]
Interesting didn't know the `ComponentPropsWithoutRef` interface. Here is also a nice documentation about this pattern: https://react-typescript-cheatsheet.netlify.app/docs/advanced/patterns_by_usecase/

Regarding your diff: I guess you need to destruct the props first, to not pass the `children` as props to the `StyledButton`. Like this:
```diff
- export const Button = (props: ButtonProps) => {
+ export const Button = ({ children, ...rest }: ButtonProps) => {
   return (
-   <StyledButton {...props}>
-     <ButtonText>{props.children}</ButtonText>
+    <StyledButton {...rest}>
+      <ButtonText>{children}</ButtonText>
     </StyledButton>
   );
 };

```

**Comment by georgiee** [comment]
let's talk through #254
