### ISSUE TITLE
Gatsby vs  Storybook: GatsbyImage

### ISSUE THREAD

**Issue by georgiee** [satellytes/satellytes.com#258]
When using `GatsbyImage` in components we don't see the images. Can we make this work?

This blog post might come in handy if we need to deal with `GatsbyImage` and related gatsby specific things in storybook.
https://paulie.dev/posts/2020/04/gatsby-recipe-storybook-js/

Actually our plugin [storybook-addon-gatsby](https://github.com/prismicio-community/storybook-addon-gatsby) does the work of adding the graphql resolvers but not dealing with the images. On the other hand we should not rebuild gatsby in storybook. I just wanted to create a small issues to think about this topic.

**Comment by georgiee** [comment]
Can we solve that? Any new development? If yes, let's explain better otherwise close this as we can't fix it easily.

**Comment by feedm3** [comment]
The official docs say that it's not possible right now. Let's keep an eye on it once in a while, but as long as we can't do anything (simple) here let's close this issue.

https://www.gatsbyjs.com/docs/how-to/testing/visual-testing-with-storybook/
