### ISSUE TITLE
Localized links in rendered Markdown

### ISSUE THREAD

**Issue by fischeversenker** [satellytes/satellytes.com#293]
It looks like our markdown renderer does not take the current language into account when turning `[...](...)` into `<a>` elements. That means that for links in our markdown files (e.g. `data-privacy-de.md`) we need to manually add `/de` to links. 

### Expected outcome
It would be nice if we wouldn't need to hardcode any locale id into the links in our Markdown.

**Comment by georgiee** [comment]
I have commented on this in a PR and created an entry in https://github.com/satellytes/satellytes.com/issues/251

The markdown renderer, which is legacy code, needs to use the `Link` component. I added it to the linked issue as we can solve that while working on the markdown renderer which we should update together with providing some more atomic ui components.

**Comment by georgiee** [comment]
We need to check if that issue persists and then we can fix it with little effort I guess.
