### ISSUE TITLE
SEO indexing issues or just a lag?

### ISSUE THREAD

**Issue by georgiee** [satellytes/satellytes.com#343]
When I search for "[staff engineer](https://www.google.com/search?hl=en&q=staff%20engineer%20satellytes)", "[How enterprises benefit from scoped npm registries satellytes](https://www.google.com/search?hl=en&q=How%20enterprises%20benefit%20from%20scoped%20npm%20registries%20satellytes)", or "[metaverse satellytes](https://www.google.com/search?q=metaverse+satellytes&hl=en)" I expected to see our content as it's available for a few days or even weeks.

I can find the older content though. Is this just an indexing lag? Can we improve that?

**Comment by feedm3** [comment]
Just checked the Google search console and it looks like some pages are not indexed:

<img width="898" alt="Screenshot 2022-01-31 at 08 02 01" src="https://user-images.githubusercontent.com/7814926/151751699-55753e0a-b614-42b0-b0b8-55c077a0fb9c.png">

<img width="1168" alt="Screenshot 2022-01-31 at 07 59 15" src="https://user-images.githubusercontent.com/7814926/151751409-9a180afd-c4f2-4413-8831-ff3e1fa8097c.png">

Usually, Google should crawl them automatically, they are even in the `sitemap.xml`: https://satellytes.com/sitemap/sitemap-0.xml

I now triggered a crawling action on all of those 4 pages manually within the Google Search Console.

**Comment by georgiee** [comment]
SEO is good right now. @feedm3 looked at it and the last time we did not have any issues after improving the semantic data as seen in the linked PR. This issue is done.
