### ISSUE TITLE
Status: dependabot

### ISSUE THREAD

**Issue by georgiee** [satellytes/satellytes.com#366]
For the current status see https://github.com/satellytes/satellytes.com/network/updates
based on the file https://github.com/satellytes/satellytes.com/blob/b41170ddf5847cbf71c831604109af0ecd648034/.github/dependabot.yml

Issues:
1. We need to build through github actions as we don't know if it's works due to the missign gatsby build (expected as they don't build on automatic PRs, @feedm3  found out about that).
2. It looks super annoying right now with the many PRs. But I I think it's just because we started. I should be better over time with fewer dependencies. dependencies are grouped by peer dependencies so gatsby update should be a single PR in the best case
3. I think we should enable auto merge for dependabot if github actions are testing & building everything. Makes it much easier to handle the single PRs

**Comment by georgiee** [comment]
we need to add [skip netlify] to the commit messages otherwise our netlify build minutes will run out I think

**Comment by feedm3** [comment]
What we need to do:
- Add `[skip ci]` to the commit messages to skip netlify builds https://www.netlify.com/blog/2019/10/10/intelligent-deploy-skipping-an-automatic-optimisation/
- Run a manual build with Github Actions, to make sure the dependency update doesn't break anything
- Make Gatbsy Cloud Build optional. That's a bit unfortunate, as they are only optional for Dependabot PRs and not manual PRs

Check https://github.com/satellytes/satellytes.com/pull/367 for the implementation.

Optionally:
- Merge Dependabot PRs automatically after all checks are green

**Comment by fischeversenker** [comment]
> Automatic merge request for Depnendabot PRs

What do you mean, @feedm3?

Generally, how do we proceed here? I guess after #367 got merged we can rebase all the open Dependabot PRs so they trigger the build GitHub Workflow? And then we merge all the green ones? 🎉

**Comment by feedm3** [comment]
Ups, my brain was somewhere else when I wrote this :D 

I mean we can add a workflow that will merge the Dependabot PRs automatically once all checks are green.

**Comment by feedm3** [comment]
I just found the Feature Request for Dependabot grouped / batched updates. The thread is locked, but it looks like it is on their roadmap. Unfortunately without an ETA: https://github.com/dependabot/dependabot-core/issues/1190

**Comment by georgiee** [comment]
I think dependabot is okay right now. Only thanks to @feedm3 efforts each Monday morning we are not drowning in PRs. So it's improvable but I don't see any way to do it right now. It's good to have an eye on that. We might even want to shorten the PR cadence time or disable it entirely and have manual dependency spikes each month instead. This issue is closed for now.
