### ISSUE TITLE
Design (optional): Parallax Scroll Image Masking

### ISSUE THREAD

**Issue by esreverse** [satellytes/satellytes.com#394]
We are using narrow full-width images as separators on the website, for example on home (https://satellytes.com/) twice. I would like the images to be full-width and full-height, but masked by the current size of the cut-out (height: 360 px). When scrolling, the cut-out should reveal the image behind. Nice parallax effect.

**Comment by georgiee** [comment]
This is a nice to have feature. Be careful because of Gatsby Image that doesn't act the same as an `img` which might make this feature more problematic. @esreverse please provide a reference page to see the effect in action. Link or Video. Thank you.

**Comment by esreverse** [comment]
https://www.w3schools.com/howto/howto_css_parallax.asp
I think it's called position:sticky.

On the link above, click this button
![EricsShot 2022-03-21 11 14 20](https://user-images.githubusercontent.com/6918281/159241746-0a38eaa5-f636-4c72-9022-3c905c2ab47a.png)

It should look like this. The mask is quite narrow in height, but the image behind it is scaled to fill the whole browser window.
![EricsShot 2022-03-21 11 14 41](https://user-images.githubusercontent.com/6918281/159241917-b2be7838-d7d3-4653-93fd-28c9d6927136.png)

**Comment by georgiee** [comment]
No sticky is a technical detail that might play a role but will confuse people if you name it like that. Thanks for the link.

**Comment by milljoniaer** [comment]
Since we agreed on doing without a parallax for now, I close this issue
