### ISSUE TITLE
FCB Case (Overview Ticket)

### ISSUE THREAD

**Issue by esreverse** [satellytes/satellytes.com#417]
Ok, let's bring this case online!

Technically, it should be a blog article with some new components. What we don't have is:
* the large purple link? maybe it can be done with markdown though
* the stats element below the first text block (team size, start, end). what ideas do you have to realize this?
* full width images
* parallax image
* the tag sections at the end of the article

*Figma link:* https://www.figma.com/file/FWlI63N28LP7BxqNqj1bGw/sy-004-(Design!)?node-id=4729%3A18247

## Stats Element
* on desktop it's in one row (48 px horizontal spacing between the blocks)
* on mobile, every element would be below each other (32px vertical spacing between the blocks)
* currently it's 3 elements, but in the future it could be used for other purposes, so it could also be 1 or e.g. 5
* label and value are always mandatory
* grab font sizes and details from Figma

## Full Width Images
* aspect ratio stays the same, so height changes when width changes

## Parallax Image
* the picture with Sané, see issue: https://github.com/satellytes/satellytes.com/issues/394
* fallback: integrate the current more narrow version like in Figma

## Tag Sections
* currently it's 2 sections, but it can be also 1 or e.g. 5 later
* headline is mandatory
* tags could be 1 or up to 20
* they are not linked at the moment, but this section could be linked tags below any article that searches for other articles with this tag, just to give you an idea where this could lead
* grab details from Figma

<details>
<summary>Screenshots 1</summary>

![dummy](https://user-images.githubusercontent.com/6918281/154031361-1fc41703-7a6a-421b-a0d3-f9de04090012.png)

![group](https://user-images.githubusercontent.com/6918281/154031353-6320d5fb-a1eb-4f24-8171-705c2866b1ef.png)

</details>

<details>
<summary>Screenshots 2</summary>

![06_DYNFCB_231121_DON](https://user-images.githubusercontent.com/6918281/154031339-43f33750-83f9-42fe-b492-f5079326b8d1.jpg)

![211217_Sane_IMA](https://user-images.githubusercontent.com/6918281/154031348-a880a265-62ff-4f79-a3de-eb714ad89546.jpg)

</details>

<details>
<summary>Screenshot (Full)</summary>

![d-article](https://user-images.githubusercontent.com/6918281/154031327-99235dbd-e4a3-4494-9c11-4ff789219612.jpg)

</details>

**Comment by georgiee** [comment]
This topic is postponed as we need to deliver the text content again.

**Comment by georgiee** [comment]
We got our updated text so let's complete this task 🙌
@milljoniaer you worked on https://github.com/satellytes/satellytes.com/pull/434 before. Does it make sense to swap the text and keep the images to get things done quickly ?

**Comment by milljoniaer** [comment]
I dont think that this makes sense, since we changed our blog posts to contentful. #434 was done via the markdown thing. 
I suggest to do the whole thing via Contentful now.

**Comment by georgiee** [comment]
ah you're right of course, sorry 😬

**Comment by milljoniaer** [comment]
Since the FCB Case is online now (see [here](https://satellytes.com/blog/post/fc-bayern-website-frontend-relaunched-by-satellytes/)), I close this issue
