### ISSUE TITLE
Generate anchors in blog posts to be able to link to specific sections

### ISSUE THREAD

**Issue by fischeversenker** [satellytes/satellytes.com#459]
### Expected outcome
As a user I want to be able to link to a specific headline in one of our blog posts. 

Example: I want to be able to link to the section "Compiling and bundling an Action" in [this blog post](https://satellytes.com/blog/boosting-developer-productivity-with-github-actions/).

### Proposed solution
I suggest to add `id` attributes (or add nested `<a id="...">` elements) in headlines and make them clickable like in [the HTML that GitHub generates from Markdown](https://github.com/satellytes/satellytes.com#component-development-with-storybook): 
![image](https://user-images.githubusercontent.com/7970458/156176797-9a88e950-63ff-40c9-bcec-0d73761e2490.png)

**Comment by georgiee** [comment]
Yeah that's a good idea, especially for the blog content but might be useful for the static content too (we had that on a single page, I think service, before).
