### ISSUE TITLE
Design: Different formfield colors

### ISSUE THREAD

**Issue by esreverse** [satellytes/satellytes.com#476]
* Formfield colors of contact form and career form are different. Please use the light version (contact) also for career.
* When formfield is focused, please make 1 px outline (inside) in our darkblue (#202840)

Currentl
![IMG_9885](https://user-images.githubusercontent.com/6918281/157199922-3330a3de-f3ec-455e-86ab-3c38f433b203.PNG)
![IMG_9886](https://user-images.githubusercontent.com/6918281/157199931-12ac1c26-ea47-4552-8149-fcbe5ead46a2.PNG)
y:

Correct:
![EricsShot 2022-03-08 09 41 02](https://user-images.githubusercontent.com/6918281/157199857-6fed7703-8153-4ff1-b338-5f94b997cf6f.png)

**Comment by georgiee** [comment]
This should be part of our refactoring efforts to remove our technical debt and will be covered through an alignment of the forms as described in https://github.com/satellytes/satellytes.com/issues/503
