### ISSUE TITLE
Lightbox for Images (Medium Zoom)

### ISSUE THREAD

**Issue by georgiee** [satellytes/satellytes.com#502]
Note: This feature looks easy but it can get difficult in details. It's a nice to have feature so use your time wisely.

We want to provide an optional lightbox effect for images that people should be able to enlarge.
This feature should be useable across the website. Blog & Content.

Initial Discussion: https://github.com/satellytes/satellytes.com/issues/323
Reference/Example (random article on medium): https://newanddigital.medium.com/from-memes-to-menace-revisiting-copium-memes-a-year-later-6c7b2cdc42ff

--
- [ ] Make sure it's useful on mobile (because of the modal window). In doubt disable on small screens and link to the original image.
- [ ] Make sure Accessibility concerns are covered (aria live etc)
- [ ] Will Gatsby Image make this task difficult to the way it's handling images (it's not a simple `img`)

Make sure to check on Gatsby Image first. If this is a large obstacle we have to postpone or cancel this feature. Otherwise continue and keep an eye on accessibility general (keyboard, screen reader) and specifically for smaller screens.

**Comment by georgiee** [comment]
There seems to be a common library for doing the "medium zoom". Let's check if this works with Gatsby Images:
https://github.com/francoischalifour/medium-zoom Here the [playground](https://codesandbox.io/s/github/francoischalifour/medium-zoom/tree/master/website).

**Comment by feedm3** [comment]
And here is the react implementation of it. Already used it, works very good and is simple to implement: 

https://github.com/rpearce/image-zoom

**Comment by milljoniaer** [comment]
Since we have a implementation now on the website, I suggest to close this issue
