### ISSUE TITLE
Provide structured data for our logo & company

### ISSUE THREAD

**Issue by georgiee** [satellytes/satellytes.com#516]
I would like to tell Google about our Logo (and maybe something else is missing in that vein?)
Find everything you need here: https://developers.google.com/search/docs/advanced/structured-data/logo

It's about adding some structural data to the header to describe which logo we want to use. 

Example:
```
  <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "Organization",
      "url": "http://www.example.com",
      "logo": "http://www.example.com/images/logo.png"
    }
    </script>

```

Then it will show up like this:
![Screenshot 2022-03-25 at 07 57 22](https://user-images.githubusercontent.com/1701755/160070216-4b47cacd-23e0-4078-b0fa-e538b96a8063.png)

Google seems to use random images from Google Maps for Satellytes right now:
![Screenshot 2022-03-25 at 07 58 17](https://user-images.githubusercontent.com/1701755/160072105-f4b9c522-3b5f-4ccc-bd3c-9e7928fe3832.png)

**Comment by milljoniaer** [comment]
According to https://thomas.vanhoutte.be/miniblog/schema-org-social-media-websites/ it should be possible to provide also Social Media Accounts and a name via structured data:

--- update ---
Google links in their documentation to https://schema.org/Organization
So all thos properties should be valid

```
 <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "Organization",
      "name":"Satellytes Digital Consulting GmbH",
      "address": {
           "@type": "PostalAddress",
           "streetAddress":"Sendlinger Straße 52",
            "addressLocality":"München",
            "addressRegion":"Bayern",
            "postalCode":"80331",
            "addressCountry":"DE"
      },
      "email": "info@satellytes.com",
      "url": "http://www.satellytes.com",
      "logo": "link-to-our-logo"
      "sameAs": [
          "https://www.linkedin.com/company/satellytes",
          "https://www.xing.com/companies/satellytesgmbh",
          "https://github.com/satellytes",
          "https://twitter.com/satellytes_beep",
      ]
    }
 </script>
```

It would also be possible to add a wikipedia page to the description, like google did or provide an own description about Satellytes 🛰️

**Comment by georgiee** [comment]
Nice what you collected ✨ 
The logo image must be 112x112px, at minimum. I guess for retina larger? I would suggest to ask our designers for an appropriate image for that view.

I also found this nice gallery of a structured data displays that I want to drop here. It also lists again the logo entry with refers to the knowledge card in google results. 
https://developers.google.com/search/docs/advanced/structured-data/search-gallery

So let's do what you have found out and put the organization data on our website. I only wonder if we put that on the landingpage only or on any page? I think a single page is enough as the root of our website.
