### ISSUE TITLE
Website Loading Flickering

### ISSUE THREAD

**Issue by georgiee** [satellytes/satellytes.com#52]
I'm reloading, reloading, reloading and you always see this flickering. Reported by @maxmarkus and I confirmed it and provide the gif here.

![satellytes](https://user-images.githubusercontent.com/1701755/100984366-efaee280-354a-11eb-9b4a-b7880c5a4701.gif)

**Comment by feedm3** [comment]
Flickering should be gone now. Background image still not perfect in regards of lighthouse score and responsiveness, but will takle that in #60
