### ISSUE TITLE
Add RSS feed to the blog page

### ISSUE THREAD

**Issue by konclave** [satellytes/satellytes.com#535]
That's the most convenient way to get the updates from multiple websites in one place. 
I'm still using RSS feeds. Maybe I'm not the only one =)
**Update:** as RSS feed already exists, maybe we should add an RSS link to the blog articles overveiew page.

**Comment by JulianAnthes** [comment]
Hi @konclave, we already have a [rss feed](https://satellytes.com/blog/rss.xml), or am I missing something?

**Comment by feedm3** [comment]
The link to the RSS feed is currently at the bottom of each blog post. 

![Screenshot 2022-04-01 at 09 12 27](https://user-images.githubusercontent.com/7814926/161213836-643dac73-a129-46f1-81e8-4487b06f5018.png)

It's missing on the blog overview page at https://satellytes.com/blog. We can ask Design to also add a link there. If the RSS feed URL is hard to find, we should also ask them to make it more prominent. Although I'm not sure if the RSS feed is used by so many people.

**Comment by konclave** [comment]
@dschu-lab @feedm3 oh, great! I just expected to see it under the blog overview page. The idea was that I see the list of articles and want to subscribe for the updates. So, it becomes just "add an RSS link to the `/blog` page`". I will update the description.

**Comment by JulianAnthes** [comment]
I think we should also refer to the rss feed inside the `header` like:

```html
<link rel="alternate" type="application/rss+xml" title="Example Feed" href="http://example.com/feed/" />
```
