### ISSUE TITLE
Improve HTML headers

### ISSUE THREAD

**Issue by feedm3** [satellytes/satellytes.com#548]
Currently, some of our pages are not using headers correctly. Especially the main page only has one `h1` and nothing else.

<img width="617" alt="Screenshot 2022-04-04 at 09 30 34" src="https://user-images.githubusercontent.com/7814926/161495179-329efd56-352c-4415-be07-26def595fefa.png">

Make sure that all our headlines are using the correct HTML headers to make the site more accessible and SEO friendly.

Some resources:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements
- https://chrome.google.com/webstore/detail/seo-meta-in-1-click/bjogjfinolnhfhkbipphpdlldadpnmhc?hl=de

**Comment by milljoniaer** [comment]
#553 dealt with this
