### ISSUE TITLE
Create a responsive <img /> component

### ISSUE THREAD

**Issue by feedm3** [satellytes/satellytes.com#60]
Use Cloudinary links to create a responsive image component. This component should be used for all images (homepage, blog posts, hero images...)

Example:
```
<img
        src="https://res.cloudinary.com/satellytes/image/upload/w_1280/e_blur:1000,q_1,f_auto/v1/satellytes-website/SY-Image_tmjwss.webp"
        srcSet={`
          https://res.cloudinary.com/satellytes/image/upload/w_300/v1/satellytes-website/SY-Image_tmjwss.webp 300w, 
          https://res.cloudinary.com/satellytes/image/upload/w_768/v1/satellytes-website/SY-Image_tmjwss.webp 768w, 
          https://res.cloudinary.com/satellytes/image/upload/v1/satellytes-website/SY-Image_tmjwss.webp 1280w
        `}
        alt=""
      />
```

This example should be somehow what must be rendered by the component. Check other best practices on how to get the best result. Also keep a look at the  lighthouse score. 

Resources:
- https://www.sitepoint.com/how-to-build-responsive-images-with-srcset/

**Comment by georgiee** [comment]
How does this relate to the new [gatsby image plugin](https://www.gatsbyjs.com/plugins/gatsby-plugin-image/) ? 
I think we can use the new StaticImage component, pass in the url from the high res remote url and gatsby will process as we know it from GatsbyImage. Will this make this feature request obsolete?

**Comment by feedm3** [comment]
We can close this issue. This was an early idea to host all images on Cloudinaty. By using gatsby-plugin-image, we don't need this anymore.
