### ISSUE TITLE
Wrap long links in blog content

### ISSUE THREAD

**Issue by georgiee** [satellytes/satellytes.com#604]
Reported by @maxmarkus 
Long links kill the layout and we should force a wrapping of that by using some css on links (something around break-word, overflow-wrap).

I can't reproduce it in Safari, not in Firefox.
Referenced article is https://satellytes.com/blog/post/cloudfront-cache-efficiency/

![Screenshot 2022-04-20 at 17 17 46](https://user-images.githubusercontent.com/1701755/164264752-e00fcb37-09f9-4b86-9963-7b0b7275e2b6.png)

**Comment by hofmann-felix** [comment]
The same problem also arises with long in-line code snippets.

(https://satellytes.com/blog/post/boosting-developer-productivity-with-github-actions/, Android, Chrome)
![Screenshot_20220421-070243_Chrome](https://user-images.githubusercontent.com/57712895/164376578-f3847077-3dfc-4ba8-badd-5404526637a3.jpg)
