### ISSUE TITLE
Integrate Personio Recruiting

### ISSUE THREAD

**Issue by georgiee** [satellytes/satellytes.com#64]
We want to fully integrate Personio Recruiting in our website.

In order to do that we need to work on two things:
1. List all open position. Accessible through the public xml feed https://satellytes.jobs.personio.de/xml
2. Create a form and submit it directly to the [Personio Recruiting API](https://support.personio.de/hc/en-us/articles/360000314338-The-Personio-Recruiting-API)

**Note:** The form submission requires us to submit the company id and an access token for recruiting. I think the access token is meant to be used on the web as the API only describe actions that can be triggered from the default applicant form (https://satellytes.jobs.personio.de/) anyway. There is no functionality around actually managing applications.

here related API note:

> **A note on spamming**
> Please be aware that the access_token in company with your company_id allows the creation of applications in your account. When building your own career page, we would recommend that you call our endpoints from a backend service, rather than from your frontend directly, in order to avoid making the token publicly accessible. In addition to this, we recommend the inclusion of a captcha or similar into your own career page to avoid bot applications.

> **Rate limiting**
> Our applicant API is a rate limit of 100 applications in 60 seconds per IP address. After submitting this amount of applications, you will need to wait 60 seconds before you can submit more applications.

Full API description: https://developer.personio.de/docs/applications-endpoint

**Comment by feedm3** [comment]
Pull requests:
- add career pages: #65 
- add a contact form for Personio: #66

**Comment by georgiee** [comment]
done & merged into `main` via #65, let's focus on fixes and polishment
