### ISSUE TITLE
RSS feed: Missing closing `<a>` tag in cover image

### ISSUE THREAD

**Issue by JulianAnthes** [satellytes/satellytes.com#646]
## What happened?

In some cases our XML in [the RSS feed](https://satellytes.com/blog/rss.xml) is rendered incorrectly. This is because the closing `<a>` tag is missing.

![rss-feed-xml-error](https://user-images.githubusercontent.com/3493187/176678130-0e73b1b1-1e41-48c0-9248-d1bc3ccc60c7.png)

## What is affected?

Inside the rss feed, all blog posts with an author linked to the hero image are affected by this bug.

## Possible solution

We need to fix the error by closing the link tag:

https://github.com/satellytes/satellytes.com/blob/873a08f565a522e49205681719d986a2b47de939/gatsby-config.ts#L156

**Comment by georgiee** [comment]
awesome that you found this and that this fixed the dev.to import (presumably) 🙌
