### ISSUE TITLE
Trailing slashes are treated wrong

### ISSUE THREAD

**Issue by maxmarkus** [satellytes/satellytes.com#67]
Eg. entering https://satellytes.com/career/325493-senior-ux-ui-designer-m-w-x/ removes the trailng slash. 

But copying and pasting this WhatsApp ends in an 404 preview. 
<img width="639" alt="Bildschirmfoto 2021-04-06 um 11 10 18" src="https://user-images.githubusercontent.com/1720843/113687760-f603c580-96c8-11eb-8e11-b399e6306f29.png">

Server routing should work also without trailing slash.

**Comment by feedm3** [comment]
`https://satellytes.com/career/325493-senior-ux-ui-designer-m-w-x` has a `301` redirect to `https://satellytes.com/career/325493-senior-ux-ui-designer-m-w-x/`. This is handled by Netlify.

Both links work for me in Whatsapp:

![image](https://user-images.githubusercontent.com/7814926/113697748-eb026280-96d3-11eb-9adf-e88fc580937a.png)

![image](https://user-images.githubusercontent.com/7814926/113697809-ff465f80-96d3-11eb-9514-933382f44495.png)

Maybe just a Netlify hickup?

**Comment by maxmarkus** [comment]
For me it is still reproducible. WhatsApp MacOS App. But in WhatsApp on Android it is working. So could be a WhatsApp bug too.

**Comment by maxmarkus** [comment]
Issue not appearing anymore. Thanks
