### ISSUE TITLE
Update About Page

### ISSUE THREAD

**Issue by verena-may** [satellytes/satellytes.com#686]
Update the "About Page" regarding the new Layout 
https://www.figma.com/file/FWlI63N28LP7BxqNqj1bGw/sy-004-(Design!)?node-id=6093%3A24595&t=B5lVnr3rV8owVoTF-4

**Changes:**
- No Headline in the Header
- Integrate Google Maps Link in the Intro-Text
- People and Office Images shown in a Collage-Layout

**German Text:**
Das ist unser erfahrenes Team aus Entwicklern und Designern. Einige arbeiten vollständig remote, einige in unserem Büro im Herzen Münchens – direkt am Sendlinger Tor.
Wir freuen uns immer über Besuch und einen gemeinsamen Kaffee.

<img width="110" alt="CleanShot 2022-12-19 at 10 01 29@2x" src="https://user-images.githubusercontent.com/75441009/208387780-3522f21d-0e5d-4e05-a3b2-7fb69698e236.png">

**Comment by timonsommer** [comment]
I started implementing this using CSS grids: 9c84e934990c2c786962e5a0ff6c27acdf8b4d94.
Here's what it looks like so far: 
<img width="297" alt="Screenshot 2022-12-30 at 16 44 22" src="https://user-images.githubusercontent.com/104005017/210088537-86fdab72-90f8-47ad-a311-bb6cc2b1acbc.png">

**Comment by abdolg** [comment]
This issues is no longer necessary because the design has been changed.
