### ISSUE TITLE
Update Menu About us -> About

### ISSUE THREAD

**Issue by verena-may** [satellytes/satellytes.com#687]
Change the menu point "About us" into "About"

<img width="383" alt="CleanShot 2022-12-17 at 13 41 22@2x" src="https://user-images.githubusercontent.com/75441009/208242373-1699189b-5528-4632-9ef8-ea62282b1cee.png">

**Comment by feedm3** [comment]
Done in https://github.com/satellytes/satellytes.com/pull/689
