### ISSUE TITLE
Replace gatsby-plugin-react-helmet with gatsby own head api

### ISSUE THREAD

**Issue by feedm3** [satellytes/satellytes.com#698]
Got this information from the build logs. The plugin can be removed an we can use the build in Gatsby API to create head entries: https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-head/

![screenshot-08-02-2023-at-09-27-03](https://user-images.githubusercontent.com/7814926/217475127-32ed89f7-7479-4551-8642-fe962bcd6a19.png)

**Comment by WiebkeFr** [comment]
The plugin is replaced with Gatsby Head API in https://github.com/satellytes/satellytes.com/pull/785.
