### ISSUE TITLE
Career page: Form message is unformatted in Personio

### ISSUE THREAD

**Issue by feedm3** [satellytes/satellytes.com#74]
The message from our career form isn't formatted anymore in Personio. This makes it quite hard to read.

**Comment by georgiee** [comment]
I tested this and it seems the API just sanitizes everything. I raised a question on the Personio discussion board:
https://developer.personio.de/discuss/60a380664cb3940034c999dc

Mostly the requests are forgotten here though. The "official" way is through Personio communitu and to raise an "idea" which is ridiculous for a clear bug.

Same happened to the webhook request. Nothing happened for weeks now.
https://developer.personio.de/discuss/5fe1f5d1757e0c002fbb14e7

I think this is a won't fix. I will monitor the personio side. Let's keep this issue open for a while and then close it sooner than later.

**Comment by georgiee** [comment]
Last feedback came on 01.06.2021 and since then we are waiting for the follow up from Personio. Let's ask in a few weeks again. No need to post an idea because the topic was picked up by the personio devs.

**Comment by georgiee** [comment]
This is just frustrating. Probably a simple line of code but nobody cares. Let's keep this issue open until we hear more. I will escalate soon.

**Comment by abdolg** [comment]
This issue is obsolete since we no longer use Personio, right? @georgiee if so please close this issue. Thank you.
