### ISSUE TITLE
Images not processing (Team)

### ISSUE THREAD

**Issue by georgiee** [satellytes/satellytes.com#783]
I uploaded some images (team page) but they are not processed even though the build succeeds (so it's wrongly deployed)

![CleanShot 2023-11-28 at 09 50 29](https://github.com/satellytes/satellytes.com/assets/1701755/3f9e074f-514b-4611-8b97-d1f2021f050b)

**Comment by milljoniaer** [comment]
This issue was resolved by adding the `GATSBY_BASE_URL` to the netlify environment variables.
